name: CI_action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to the latest version

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3  # Updated to the latest version
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: ./app  # Specify working directory here

      - name: Run the tests
        run: npm test
        working-directory: ./app  # Specify working directory here

      - name: Build
        run: npm run build
        working-directory: ./app  # Specify working directory here
