name: CI_action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Updated to the latest version

      - name: List files in the root directory
        run: ls -la

      - name: List files in the worksheet2 directory
        run: ls -la ./worksheet2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1  # Updated to the latest version
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: ./worksheet2/my-react-app  # Correct working directory

      - name: Run the tests
        run: npm test
        working-directory: ./worksheet2/my-react-app  # Correct working directory

      - name: Build
        run: npm run build
        working-directory: ./worksheet2/my-react-app  # Correct working directoryy


